### ISSUE TITLE
Using edit tags to execute rules

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation#114]
Hi again,
For running the validation, it appears that each of the compiled edits has its own definition of the identifiers such as `IF138` or `NAACCR-00001` that it uses for selecting rules rather than the `Edit Tags` like `N0404` that are core to GenEdits. As you mentioned in issue #14 this property is strictly speaking optional, as such could be a big change to rely on it within the framework.

This is not a feature suggestion, but rather an open ended question: how do you suggest using `Edit Tags` to run the associated rules?

My current plan is to write a script that will scrape the Rule definitions from the source of the edits and populate a map to translate from `Edit Tags` to `ID`, but I was wondering if either a resource for that already exists and is maintained or if you had any suggestions you thought might be better and more robust than that.

Thanks, James.

**Comment by depryf** [comment]
Hi James.

As always, lots of a history behind all this. 

This framework pre-dates the Genedits tags. At the time, the names were used as edit identifiers, but they changed over time, making them very poor identifiers. 

Even the tags are not great because they are only unique within a metafile (which is perfectly fine for the Genedits world because those software only run one metafile at a time, but this framework has the ability of loading several metafiles together). 

Anyway, I think using a map of tags/ID will work fine, with one caveat. If you try to initialize the engine with both the SEER and the NAACCR edits, then the tags won't be unique. That's because many (most) SEER edits also exists in the NAACCR metafile. If you do that, then just pick which edit you want to use (SEER vs NAACCR). If you only load NAACCR edits, that won't be an issue.

I am a bit curious why you mention using a script though. Can't you just build an internal map after the edits are initialized?

```java
        Map<String, String> tagsToId = new HashMap<>();
        for (Validator v : ValidationEngine.getInstance().getValidators().values())
            for (Rule r : v.getRules())
                tagsToId.put(r.getTag(), r.getId());
```

Are you trying to extract that information from the XML file itself?

**Comment by jpalmerpivotal** [comment]
Many thanks for reminding me that `Edit Tags` are accessible within the framework, in my head I was very focused on getting rules by Tag and forgot that doesn't matter when you just want all the rules.

As always I appreciate the context explaining the situation, it really does help to both understand what the situation is and how it got that way.

I will go forward with the solution you provided.

Thanks again!
